#!/bin/bash

if [ -z "$1" ]; then
    RPMNAME=$(basename "$PWD")
    NAME=${RPMNAME:6}
else
    NAME=$1
    RPMNAME=npmjs-${NAME//[\@\/]/-}
    RPMNAME=${RPMNAME//--/-}
fi

echo $NAME
echo $RPMNAME

VERSION=$(npm view $NAME version)

# Remove previous tarballs
rm -f $RPMNAME-*.tar.gz

# Generate source tarball

npm install $NAME
mv node_modules/$NAME $RPMNAME-$VERSION
mv node_modules $RPMNAME-$VERSION
{
    # Remove all hidden files and directories
    find $RPMNAME-$VERSION/node_modules -mindepth 1 -name '.*' -exec rm -rf {} \;
    # Remove all temp files
    find . -name '*.bak' -delete
    find . -name '*.swp' -delete
    find . -name '~*' -delete
    find . -name '*~' -delete
    # Remove all execute bit from files of sub modules
    chmod -R -x+X $RPMNAME-$VERSION/node_modules
} &> /dev/null
tar -pcvzf $RPMNAME-$VERSION.tar.gz $RPMNAME-$VERSION >/dev/null
rm -rf package-lock.json $RPMNAME-$VERSION

# Generate spec file

if [ ! -f "$RPMNAME.spec" ]; then
    rpmdev-newspec -t nodejs $RPMNAME
fi

# Fill %npm_name variable

sed -i "s~\[npm_name\]~${NAME@Q}~g" $RPMNAME.spec

# Update version number

sed -i "s/Version\:.*/Version:        $VERSION/g" $RPMNAME.spec
